#!/usr/bin/env bash

export_runtime_init() {
  PK3S_EXPORT_METADATA_COMMAND=""
  PK3S_EXPORT_METADATA_SUBJECT_KIND=""
  PK3S_EXPORT_METADATA_SUBJECT_REF=""
  PK3S_EXPORT_METADATA_ARTIFACT_NAME=""
  PK3S_EXPORT_METADATA_INTERACTIVE=""
  PK3S_EXPORT_METADATA_TELEMETRY_ENABLED=""
  PK3S_EXPORT_ENV_KEYS=()
  unset PK3S_EXPORT_ENV_VALUES
  declare -gA PK3S_EXPORT_ENV_VALUES=()
}

export_runtime_shell_escape() {
  printf "%s" "$1" | sed "s/'/'\\\\''/g"
}

export_runtime_json_escape() {
  printf '%s' "$1" | sed \
    -e 's/\\/\\\\/g' \
    -e 's/"/\\"/g' \
    -e ':a;N;$!ba;s/\n/\\n/g' \
    -e 's/\r/\\r/g' \
    -e 's/\t/\\t/g'
}

export_runtime_add_env() {
  local key="$1"
  local value="$2"
  if [[ -z "${PK3S_EXPORT_ENV_VALUES[$key]+x}" ]]; then
    PK3S_EXPORT_ENV_KEYS+=("$key")
  fi
  PK3S_EXPORT_ENV_VALUES["$key"]="$value"
}

export_runtime_set_metadata() {
  local key="$1"
  local value="$2"
  case "$key" in
    command)
      PK3S_EXPORT_METADATA_COMMAND="$value"
      ;;
    subject_kind)
      PK3S_EXPORT_METADATA_SUBJECT_KIND="$value"
      ;;
    subject_ref)
      PK3S_EXPORT_METADATA_SUBJECT_REF="$value"
      ;;
    artifact_name)
      PK3S_EXPORT_METADATA_ARTIFACT_NAME="$value"
      ;;
    interactive)
      PK3S_EXPORT_METADATA_INTERACTIVE="$value"
      ;;
    telemetry_enabled)
      PK3S_EXPORT_METADATA_TELEMETRY_ENABLED="$value"
      ;;
    *)
      printf 'Unsupported export metadata key: %s\n' "$key" >&2
      return 1
      ;;
  esac
}

export_runtime_write_install_config() {
  local target_path="$1"
  local key escaped_value
  {
    printf '# Generated by productive-k3s-core export runtime\n'
    for key in "${PK3S_EXPORT_ENV_KEYS[@]}"; do
      escaped_value="$(export_runtime_shell_escape "${PK3S_EXPORT_ENV_VALUES[$key]}")"
      printf "export %s='%s'\n" "$key" "$escaped_value"
    done
  } > "${target_path}"
}

export_runtime_write_manifest() {
  local target_path="$1"
  {
    printf '{\n'
    printf '  "schema_version": "1",\n'
    printf '  "command": "%s",\n' "$(export_runtime_json_escape "${PK3S_EXPORT_METADATA_COMMAND}")"
    printf '  "subject": {\n'
    printf '    "kind": "%s",\n' "$(export_runtime_json_escape "${PK3S_EXPORT_METADATA_SUBJECT_KIND}")"
    printf '    "ref": "%s",\n' "$(export_runtime_json_escape "${PK3S_EXPORT_METADATA_SUBJECT_REF}")"
    printf '    "artifact_name": "%s"\n' "$(export_runtime_json_escape "${PK3S_EXPORT_METADATA_ARTIFACT_NAME}")"
    printf '  },\n'
    printf '  "runtime": {\n'
    printf '    "interactive": "%s",\n' "$(export_runtime_json_escape "${PK3S_EXPORT_METADATA_INTERACTIVE}")"
    printf '    "telemetry_enabled": "%s"\n' "$(export_runtime_json_escape "${PK3S_EXPORT_METADATA_TELEMETRY_ENABLED}")"
    printf '  }\n'
    printf '}\n'
  } > "${target_path}"
}

export_runtime_core_runtime_paths() {
  cat <<'EOF'
LICENSE
README.md
productive-k3s-core.sh
scripts/productive-k3s-core.sh
scripts/addons-runtime.sh
scripts/addon-host-runtime.sh
scripts/runtime-contract.sh
scripts/component-versions.sh
scripts/preflight-host.sh
scripts/apply.sh
scripts/backup.sh
scripts/validate.sh
scripts/cleanup.sh
scripts/rollback.sh
scripts/send-telemetry.sh
scripts/send-telemetry-event.sh
scripts/export-runtime.sh
EOF
}

export_runtime_copy_core_runtime() {
  local repo_root="$1"
  local bundle_root="$2"
  local relative_path

  while IFS= read -r relative_path; do
    [[ -n "${relative_path}" ]] || continue
    mkdir -p "${bundle_root}/$(dirname "${relative_path}")"
    cp -R "${repo_root}/${relative_path}" "${bundle_root}/${relative_path}"
  done < <(export_runtime_core_runtime_paths)

  chmod +x "${bundle_root}/productive-k3s-core.sh" "${bundle_root}/scripts/productive-k3s-core.sh"
}

export_runtime_write_stack_install_script() {
  local target_path="$1"
  local artifact_name="$2"
  shift 2
  local arg

  {
    printf '#!/usr/bin/env bash\n'
    printf 'set -euo pipefail\n\n'
    printf 'SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"\n'
    printf 'if [[ -f "${SCRIPT_DIR}/install-config.env" ]]; then\n'
    printf '  # shellcheck disable=SC1091\n'
    printf '  source "${SCRIPT_DIR}/install-config.env"\n'
    printf 'fi\n\n'
    printf 'exec "${SCRIPT_DIR}/productive-k3s-core.sh" stack install --tgz "${SCRIPT_DIR}/%s"' "${artifact_name}"
    for arg in "$@"; do
      printf " '%s'" "$(export_runtime_shell_escape "${arg}")"
    done
    printf ' "$@"\n'
  } > "${target_path}"

  chmod +x "${target_path}"
}

export_runtime_write_readme() {
  local target_path="$1"
  local subject_ref="$2"
  local artifact_name="$3"
  cat > "${target_path}" <<EOF
# Productive K3S Exported Stack Bundle

This bundle replays the exported stack installation for \`${subject_ref}\`.

## Contents

- \`install.sh\` replays the exported installation using the bundled Core runtime.
- \`${artifact_name}\` is the packaged stack artifact consumed by the installer.
- \`install-config.env\` freezes exported environment defaults for this bundle.
- \`manifest.json\` records the exported command metadata.

## Usage

\`\`\`bash
./install.sh
\`\`\`

This bundle is self-contained with respect to Productive K3S tooling, but it may still require host prerequisites and network access at install time.
EOF
}
